### ISSUE TITLE
Error when installing the package via pip

### ISSUE THREAD

**Issue by danitico** [watson-developer-cloud/assistant-dialog-flow-analysis#16]
When installing your package, the following error is thrown
```
#warning "Using deprecated NumPy API, disable it with " \
     ^
    pandas/_libs/src/ujson/python/objToJSON.c:194:12: error: use of undeclared identifier 'NUMPY_IMPORT_ARRAY_RETVAL'
        return NUMPY_IMPORT_ARRAY_RETVAL;
               ^
    1 warning and 1 error generated.
    error: command 'clang' failed with exit status 1
```

**Comment by danitico** [comment]
It seems there is a dependency problem between 1.0.7 version of you package and the 0.24.2 version of pandas

**Comment by ayaeli** [comment]
@danitico can u share more details on your environment, and your version of numpy?  Are you able to pip install pandas 0.24.2 in your environment?  
Our current list of dependencies is here.  The ~= specifies a compatible version of pandas 0.24.0.  We don't require specific numpy version other than the one that pandas will depend on.  
```
    install_requires=[
        'pandas~=0.24.0',
        'nltk>=3.4.0',
        'textblob>=0.15.3',
        'scikit-learn>=0.21.3',
        'tqdm>=4.31.1',
        'ipywidgets>=7.4.2',
        'ibm-watson>=4.3.0',
        'plotly>=4.5.0',
        'requests>=2.18.4'
    ],
```
In our testing environment we install the library on a clean anaconda/python3 docker.   In this environment, after installing our library we end up with these versions:
```
numpy==1.18.1
pandas==0.25.3
```

**Comment by danitico** [comment]
Good morning @ayaeli  ! Sorry for late replying. I'm using poetry as the virtual environment. The version of python that I'm using is 3.8.5. When installing the dependencies, first im installing the dependencies from requirements.txt and then I'm installing your package. The installation process breaks when updating the pandas package from 0.25.3 to 0.24.2

**Comment by ayaeli** [comment]
Hi @danitico. So it seems that our previous pandas~=0.24.0 criteria didn't support Python3.8.5 environments. I am changing the criteria now to  'pandas>=0.24.0,<1.0.0' which will install 0.25.3 which does install/compile in Python 3.8.5.  Will push the change today.   Let me know if it doesn't solve your issue.

**Comment by ayaeli** [comment]
The change will be update in version 1.0.9 which will be available in a few minutes... https://pypi.org/project/conversation-analytics-toolkit
